services:
  m3uproxy:
    container_name: m3uproxy
    image: m3uproxy
    build: .
    ports:
      - "7654:7654"
    environment:
      - TZ=Europe/Lisbon
      - M3U_URL=https://github.com/LITUATUI/M3UPT/raw/main/M3U/M3UPT.m3u
      # - PROXY_PORT=7654
      # - DEFAULT_UA=Mozilla/5.0 (X11; Linux x86_64; rv:149.0) Gecko/20100101 Firefox/149.0
    restart: unless-stopped
